theme = "catppuccin_mocha"

[editor]
auto-format = true
auto-pairs = true
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 100
line-number = "relative"
mouse = true
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "│"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"